version: "2"
services:
  yamlEditor:
    restart: always
    image: nginx
    container_name: yamlEditor
    volumes:
      - "./dist:/usr/share/nginx/html:ro"
    environment:
      - VIRTUAL_HOST=yaml.14159.ninja
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=yaml.14159.ninja
      - LETSENCRYPT_EMAIL=arthur.juchereau@gmail.com
networks:
  default:
    external:
      name: root_default
